### ISSUE TITLE
Support for specifying categories in emails

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-email-service#14]
@sachin-maheshwari @mtwomey we need this support for connect notification emails.

https://sendgrid.com/docs/API_Reference/SMTP_API/categories.html

fyi @vic-topcoder

**Comment by sachin-maheshwari** [comment]
@vikasrohit  added all requirements in PR - https://github.com/topcoder-platform/tc-email-service/pull/15

Expecting following payload - 
{
"topic": "email.project.created",
"originator": "tc-notifications",
"timestamp": "2018-04-06T00:00:00",
"mime-type": "application/json",
"payload": {
"data": {
"subject": "3001032",
"name": "sachin m"
},
"recipients" : ["tc@mailinator.com"],
"from" : "tc@topcoder.com",
"categories" : ["a", "b"],
"cc" : ["cc@topcoder.com"],
"bcc": ["bcc@topcoder.com"]
}
}

Note - There is some build issue at CircleCI today.
